- CHANGELOG.md
- src/steps/check-plugin-requirements.js
- src/supported-remote-plugin-versions.js
Bump minimum remote plugin versions and add minimum version reason to error message. See Changelog for more info
> release 0.5.0

- .test-runtime/__tests__/integration/schema/__snapshots__/integrity.test.js.snap
- .test-runtime/__tests__/integration/schema/__snapshots__/query-generation.test.js.snap
- CHANGELOG.md
- package.json
- src/models/gatsby-api.js
published in `gatsby-source-wordpress-experimental@0.7.4`
Fixes #6
> exclude more enqueued types by default

- src/steps/source-nodes/create-nodes/process-node.js
This branch updates the call to `fluid` by passing the `pathPrefix` option configured at the top level of a Gatsby configuration, rather than one from the plugin's own `pluginOptions`. This change means that if `gatsby build` is called without `--prefix-paths`, the `helpers.pathPrefix` will be an empty string, which is the correct behaviour.
> Fix: Use path prefix from helpers

- docs/features/preview.md
This branch removes the `/8000` from the example ngrok preview URLs.
> Remove port from ngrok preview URL path

- CHANGELOG.md
- package.json
- src/steps/source-nodes/fetch-nodes/fetch-nodes-paginated.js
- src/steps/source-nodes/update-nodes/content-update-interval.js
- src/steps/source-nodes/update-nodes/fetch-node-updates.js
- src/steps/source-nodes/update-nodes/wp-actions/index.js
Previously, if WP went down for a moment, it would cause the develop delta checker to fail the process. Now it will wait until WP comes back up and then resume:
Published in `gatsby-source-wordpress-experimental@1.2.4`
> Add refetcher delayed retry with logging

- src/utils/format-log-message.js
Running white text on blue background doesn't work on light terminal themes.
To be safe, we should use chalk's default `inverse` modifier.
Tested on dark and light themes.
Reference: https://github.com/chalk/chalk#modifiers
Addresses #57
**Current**
**Proposed solution (`inverse`)**
> CLI: use chalk inverse() to safely support multiple terminal themes

- docs/tutorials/building-a-new-site-wordpress-and-gatsby.md
WordPress pages do not have any excerpt only posts have it.
> Fix code example

- docs/themes-starters-examples.md
Adds an open source [Gatsby WooCommerce theme demo](https://gatsby-woocommerce-theme.netlify.app/) url and [source code.](https://github.com/imranhsayed/gatsby-woocommerce-themes)
> Add Gatsby WooCommerce Theme in the doc

- docs/themes-starters-examples.md
Hi 👋 
I created a starter blog for gatsby-source-wordpress-experimental that I think has a valuable use case between twenty-twenty and the alpha starter.
I would really love for it to be featured as a starter in the documentation here 😄
> Add starter blog

- src/models/image-nodes.js
- src/steps/source-nodes/create-nodes/create-remote-media-item-node.js
- in the case where the same image gets referenced both in an ACF (without size spec) and within HTML
then getFileNodeByMediaItemNode
will return a medianode rather than
the expected file node
- this patch avoids overwriting the
`nodeMetaByUrl` cache
as well as ensuring that
`getFileNodeByMediaItemNode` will
always return a fileNode
- note that I am not certain that both changes are strictly needed 
- fixes #153
> fix nodeMetaByUrl caching issue

- src/steps/source-nodes/create-nodes/create-remote-media-item-node.js
- in the case where the cached node is no longer in the node tree
(possibly due to a refresh)
then we were trying to dereference `node.internal` when
`node` was `undefined`
> fix undefined dereference in case the cached node no longer exists

- .test-runtime/.env.test
- CHANGELOG.md
- src/steps/source-nodes/update-nodes/source-previews.js
Fixed a bug where a Preview safeguard was preventing the usage of Preview with bedrock/roots (or any other setup that requires the gql endpoint to be used as /?graphql).
Closes #185
> fix preview for /?graphql

- .test-runtime/__tests__/integration/schema/__snapshots__/gatsby-image.test.js.snap
- .test-runtime/__tests__/integration/schema/gatsby-image.test.js
- CHANGELOG.md
- package.json
- src/steps/source-nodes/create-nodes/create-nodes.js
- src/steps/source-nodes/create-nodes/process-node.js
- the `options.type[typename]type.beforeChangeNode` api was not running when creating all nodes, just when updating nodes. This now runs before all node updates (create, update, delete).
- When replacing images with Gatsby images in html fields, only the first instance of an image was being replaced if there were more than 1 identical HTML <img /> strings.
> Fix: beforeChangeNode and duplicate img tags

- .test-runtime/src/components/template-parts/blog-post.js
- .test-runtime/src/templates/index.js
- .test-runtime/src/templates/single/Page.js
- .test-runtime/src/templates/single/Post.js
- CHANGELOG.md
- src/models/gatsby-api.js
- src/steps/create-schema-customization/type-filters.js
- src/steps/source-nodes/create-nodes/create-remote-media-item-node.js
- src/steps/source-nodes/create-nodes/process-node.js
- src/steps/source-nodes/fetch-nodes/fetch-referenced-media-items.js
- src/utils/cache.js
Closes #206 and #70
- 404 images will no longer fail the build during `gatsby develop` but will continue to fail the build in production builds.
- Media item fetch errors now include the name of the parent step in which the MediaItem File node was being fetched.
- When fetching html media item files, non-404 error codes now return more helpful information about which media item is having the problem.
- 404ing images in production now have an extra line to the error message explaining that the build failed to prevent deploying a broken site.
- MediaItem.remoteFile has been deprecated for a few months, querying for it now throws an error.
> Feat: add media item parent error context and allow 404s in develop

- CHANGELOG.md
- package.json
- src/steps/check-plugin-requirements.js
@acao fyi I moved the isWpGatsby check here because it turns out the order of checks here matters to get reliable errors 😱 
Related to https://github.com/gatsbyjs/gatsby-source-wordpress-experimental/issues/132
> check isWpGatsby first

- plugin/src/utils/format-log-message.js
> fix: blue text works better across themes instead of blue background

- docs/plugin-options.md
- plugin/package.json
- plugin/src/models/gatsby-api.js
- plugin/src/steps/source-nodes/create-nodes/create-remote-media-item-node.js
- plugin/src/steps/source-nodes/fetch-nodes/fetch-referenced-media-items.js
When creating a starter and using the official WP theme unit test data (which includes a 30 mb video file) I was completely unable to run a build because files this large take a very long time for Gatsby to download. I have Gigabit internet and the file downloads in a second via the browser but because Gatsby can't handle files this large very well, it kept timing out and retrying before eventually failing the build.
This new option `maxFileSizeBytes` adds a configurable max file size beyond which Gatsby will not try to fetch and process the remote file.
I'm pushing this through as a bug fix because knowing how fast my internet is, this appears to simply be a current Gatsby limitation. This will not be considered a breaking change for folks and will likely unblock folks who appear to have …
> Feat: add max filesize option

- plugin/src/steps/source-nodes/create-nodes/process-node.js
fixes issue #151
note that this will only work with images from the same source as the configured wordpress host
> fix: imageMaxWidth overrides maxWidth

- plugin/src/utils/fetch-graphql.js
- plugin/src/utils/report.js
if we get an HTML response when checking whether the schema URL is valid, we make a more minimal, successive request that tests appending `/graphql` to the URL. it either throws an error that instructs the user to update their config, or it fails quietly and goes on to handle the HTML response as before.
> feat: test /graphql in case provided url fails

- CHANGELOG.md
- plugin/src/steps/source-nodes/update-nodes/wp-actions/delete.js
- plugin/src/steps/source-nodes/update-nodes/wp-actions/update.js
- starters/gatsby-starter-wordpress-blog/gatsby-config.js
> Fix: WP node delete action can fail when type is excluded

- .gitignore
- CHANGELOG.md
- plugin/package.json
- plugin/src/models/preview.ts
- plugin/src/steps/preview/cleanup.ts
- plugin/src/steps/preview/index.ts
- plugin/src/steps/source-nodes/index.js
- plugin/src/steps/source-nodes/update-nodes/wp-actions/update.js
- Incremental builds were not properly fetching delta updates because the inc builds runner keeps around plugin state, and this plugin was assuming it didn't.
- ENABLE_GATSBY_REFRESH_ENDPOINT was being used to determine wether or not we were in preview mode. Inc builds also uses this env variable which was causing problems. We now track wether we're in preview mode using internal state instead.
- `updateSchema` was being called outside development which was causing problems where it would freeze Gatsby's state machine. This was only meant to be called in development and so has been scoped to NODE_ENV=development.
> Fix: only run preview logic in preview mode

- plugin/src/steps/source-nodes/create-nodes/process-node.js
- in case an anchor link has query params
the URL was not properly rewritten
> fix: ensure that urls with query params are rewritten

- plugin/package.json
- starters/gatsby-starter-wordpress-blog/package.json
- yarn.lock
Gatsby core recently removed `cache-manager-fs-hash` which this plugin was importing. Unfortunately this plugin didn't have it declared as a dependency.
> Fix: add missing packages

- CHANGELOG.md
- plugin/src/steps/source-nodes/update-nodes/content-update-interval.js
This work is tied to https://github.com/gatsbyjs/wp-gatsby/pull/62
This is ready for review but not to be merged. Just doing some manual testing now.
> fix: disable content update polling when refresh is enabled

- CHANGELOG.md
- plugin/src/steps/preview/index.ts
- plugin/src/steps/preview/on-create-page.ts
This is currently released as a canary `gatsby-source-wordpress-experimental@3.1.4--beta.3`
- Fixes a timing issue between PINC builds and WPGatsby. Also improves the timing of regular Preview. In this plugin all that's done is the preview node modified time is added to the pageContext of the page being previewed.
- When receiving preview data from the wrong url, it no longer fails the build
> Feat: support pinc builds and improve regular preview timing

- docker/wordpress/Dockerfile
Tests aren't able to be run currently because our Google Cloud account needs some love. Temporarily storing our zip on WPE until after the holiday. 
https://github.com/gatsbyjs/gatsby-source-wordpress-experimental/pull/321#issuecomment-734492951
> fix: temporarily use WPE to host our uploads zip

- CHANGELOG.md
- docs/plugin-options.md
- plugin/src/models/develop.ts
- plugin/src/models/gatsby-api.ts
- plugin/src/models/index.ts
- plugin/src/steps/check-plugin-requirements.js
- plugin/src/steps/declare-plugin-options-schema.js
- plugin/src/steps/ingest-remote-schema/diff-schemas.js
- plugin/src/steps/ingest-remote-schema/index.js
- plugin/src/steps/source-nodes/index.js
- plugin/src/steps/source-nodes/update-nodes/content-update-interval.js
- plugin/src/steps/source-nodes/update-nodes/fetch-node-updates.js
- plugin/src/steps/source-nodes/update-nodes/wp-actions/index.js
- plugin/src/steps/source-nodes/update-nodes/wp-actions/update.js
- plugin/src/utils/graphql-queries.js
Fixes #318 
In addition, I've made adjacent changes related to this issue to make sure our DX doesn't degrade by fixing this.
- Version 3.0.0 made an attempt to remove expensive schema diffing at the beginning of each preview or delta update. The strategy was that when a GraphQL query to WPGraphQL failed, it would try to re-run createSchemaCustomization internally to recover and rebuild our internal sourcing queries before trying to make the query again. Unfortunately this caused issues because more recent versions of Gatsby do not allow createSchemaCustomization to be called in this way. This version reverts to the earlier behaviour where the remote schema md5 is diffed on every build or preview.
- Because of the above issue, automatic schema updates during `gatsby develop` also failed …
> Fix: update schema breaks preview

- CHANGELOG.md
- plugin/src/steps/preview/cleanup.ts
- plugin/src/steps/preview/index.ts
- plugin/src/utils/report.js
- plugin/src/utils/run-steps.js
This PR improves previews for new post drafts.
- Preview errors for brand new draft posts were not being passed back to Gatsby properly. This is now fixed :)
- The full error message is now passed back to the Gatsby preview template instead of just the generic name of the step in which the error ocurred.
- In order to make new post draft previews not cause 404 errors in Gatsby, a dummy page-data.json is generated before PREVIEW_SUCCESS is sent back to WPGatsby. Now WPGatsby will read this dummy file instead of getting a 404. This speeds up new post draft previews and eliminates a long trail of 404 errors in the Gatsby Preview instance logs.
closes #320
> Fix: preview draft posts

- src/steps/source-nodes/create-nodes/process-node.js
This changes the quantifier of the regex, to include `href="/"` urls to be prefixed.
> fix: pathPrefix quantifier to include relative urls to root

- CHANGELOG.md
- docs/contribution.md
- docs/debugging-and-troubleshooting.md
- docs/plugin-options.md
- plugin/src/models/gatsby-api.ts
- plugin/src/steps/declare-plugin-options-schema.js
- plugin/src/steps/preview/cleanup.ts
- plugin/src/steps/source-nodes/create-nodes/create-remote-file-node/index.js
- plugin/src/steps/source-nodes/create-nodes/create-remote-media-item-node.js
- plugin/src/steps/source-nodes/fetch-nodes/fetch-nodes.js
- plugin/src/utils/fetch-graphql.js
- plugin/src/utils/report.js
this trades out the env variable for `requestConcurrency` for two different plugin options
> feature: seperate plugin options for concurrency limits, better errors

- CHANGELOG.md
- docker-compose.yml
- plugin/package.json
- plugin/src/steps/source-nodes/update-nodes/content-update-interval.js
- plugin/src/steps/source-nodes/update-nodes/wp-actions/index.js
- plugin/src/supported-remote-plugin-versions.js
- test-site/__tests__/integration/schema/__snapshots__/integrity.test.js.snap
- test-site/__tests__/integration/schema/__snapshots__/query-generation.test.js.snap
- Actions are no longer deduped when watching for WP changes. This is a breaking change because WPGatsby had to change in order to make this happen. So we need to change our compatibility API ranges to ensure regular functionality around this keeps working. If only WPGatsby was updated but not the source plugin, content updates would stop working. This makes it a breaking change even though for a user everything seems the same in the case that they update both plugins. Under the hood this is a huge improvement for the amount of resources the source plugin and WPGatsby are consuming and will result in less build failures.
Related to https://github.com/gatsbyjs/wp-gatsby/pull/68
> Feat: update the source plugin to work with WPGatsby v0.7.0

- CHANGELOG.md
- plugin/src/steps/ingest-remote-schema/diff-schemas.js
- plugin/src/steps/source-nodes/create-nodes/create-remote-media-item-node.js
- plugin/src/steps/source-nodes/create-nodes/process-node.js
- Added an early return for when a MediaItem node has no mediaItemUrl in order to prevent errors when we later expect that this field exists. This can happen when the remote server returns a different type of node in place of a media item node or when the remote server has some corrupt data and this field is not returned.
- When a MediaItem node could not be fetched while transforming images in html, we fetch the file directly and create a File node from it instead. These file nodes were not being cached as part of the hardCacheData api. They are now properly cached in this situation.
- Changed the hueristic for when to clear the data hard cache from an md5 of the entire plugin options object to an md5 of the url option + the type options object. This means the hard cache will clear less …
> Fix: TypeError: Cannot read property 'includes' of undefined during createStaticFiles

- .gitignore
- CHANGELOG.md
- plugin/src/utils/graphql-queries.js
This updates the action monitor queries to order by modified date instead of created date.
> Update action monitor queries to order by date

- README.md
This will make it so the emojis render on other sites like https://www.gatsbyjs.com/plugins/gatsby-source-wordpress-experimental/?=wordpress-exp
> chore: use unicode emojis rather than the github shortcut

- CHANGELOG.md
- plugin/src/steps/source-nodes/update-nodes/wp-actions/update.js
- There was an errant log that was calling all incremental updates preview updates. It now distinguishes between previews and regular data updates.
> Fix: disginguish preview vs data update logging

- CHANGELOG.md
- plugin/src/models/gatsby-api.ts
- plugin/src/steps/create-schema-customization/transform-fields/transform-object.js
- plugin/src/steps/source-nodes/before-change-node/menu-item.js
- plugin/src/steps/source-nodes/before-change-node/menu.js
Originally this PR was supposed to just be for deleting menu items when their parent menu was deleted, but I uncovered a few bugs along the way that needed to be fixed for this to work properly:
- GraphQL resolvers were previously attempting to lazy fetch nodes if the node isn't found in Gatsby. This is undesired behaviour because it will slow down resolvers considerably for any connections to deleted nodes. This behaviour was originally only intended for MediaItem nodes which could be set to be fetch lazily in resolvers. The fix here is to scope this behaviour only to MediaItem nodes and only when the MediaItem.lazyNodes option is enabled.
- Due to a WPGraphQL bug where menu items can have a different id depending on which entry point they were fetched from, we had a problem of …
> Fix: delete menu items when menus are deleted (and more)

- CHANGELOG.md
- docs/features/preview.md
- docs/plugin-options.md
- plugin/package.json
- plugin/src/models/gatsby-api.ts
- plugin/src/steps/create-schema-customization/transform-fields/transform-object.js
- plugin/src/steps/declare-plugin-options-schema.js
- plugin/src/steps/ingest-remote-schema/diff-schemas.js
- plugin/src/steps/ingest-remote-schema/introspect-remote-schema.js
- plugin/src/steps/preview/index.ts
- plugin/src/steps/source-nodes/index.js
- plugin/src/steps/source-nodes/update-nodes/wp-actions/update.js
- yarn.lock
- Restored lazy nodes resolvers for all nodes in previews. Because of the default preview preset, removing lazy nodes in the last version from everything except media item nodes ended up breaking previews that previously relied on things working this way. So in preview mode lazy nodes in resolvers is restored.
- In Previews when the schema changed all nodes were being refetched. This is only desireable when the code also changes, because previews have no way to automatically adapt to schema changes. Schema updates in previews no longer refetch all nodes.
- Added a preview debug mode which outputs relevant information for debugging Previews.
- Added a debug option to print the diff of the previous and next schema to the terminal output when the remote schema changes. This option is …
> Feat: preview debug mode

- CHANGELOG.md
- docs/plugin-options.md
- plugin/src/models/gatsby-api.ts
- plugin/src/steps/declare-plugin-options-schema.js
- plugin/src/steps/preview/index.ts
- Lowered `options.schema.previewRequestConcurrency` to 5.
- Added a sinceTimestamp where arg to preview sourcing so that only previews created in the last 10 minutes are sourced.
> Fix: account for stale previews

- CHANGELOG.md
- plugin/src/steps/create-schema-customization/transform-fields/transform-object.js
- starters/gatsby-starter-wordpress-blog/package.json
- test-site/package.json
- Restored `type.MediaItem.lazyNodes` option which broke in a previous preview optimization release.
> Fix: media item lazynodes

- docs/plugin-options.md
- generate-plugin-options-docs.js
- package.json
- plugin/src/steps/declare-plugin-options-schema.ts
- plugin/src/steps/index.ts
- prettier.config.js
Well this was a hard one to figure out. Gatsby is using the deprecated version of Joi for which there are no docs. I had changed out plugin options schema to work with the latest joi version (not realizing Gatsby isn't using this) so I could generate our plugin options.. well this resulted in Gatsby swallowing the joi error somehow and the build crashing on something completely unrelated... I finally figured out what was causing it by trial and error (it was a default value in the joi schema that was a string where the actual field is not a string and latest joi allows examples that are strings where the deprecated Gatsby version only allows examples that are of the type of the field...
> Fix: broken plugin options schema

- docs/features/media-item-processing.md
- plugin/src/steps/preview/cleanup.ts
- starters/gatsby-starter-wordpress-blog/gatsby-config.js
- starters/gatsby-starter-wordpress-blog/package.json
- yarn.lock
This addition to the starter + docs allows querying the public URL of a file directly.
```graphql
{
allWpPost {
nodes {
featuredImage {
node {
localFile {
publicURL
}
}
}
}
}
}
```
> Docs: Add File.publicURL documentation

- docs/tutorials/index.md
- docs/tutorials/transforming-data.md
- package.json
- plugin/src/steps/preview/cleanup.ts
- yarn.lock
This mini tutorial explains how to transform node data on its way to Gatsby. This tutorial is intentionally brief as it's only meant for advanced developers who are building Gatsby plugins or very much know what they're getting into.
> Docs: add transforming data tutorial

- docs/plugin-options.md
- plugin/package.json
- plugin/src/steps/declare-plugin-options-schema.ts
- yarn.lock
options.type.[typename].where was missing. Not anymore :D
> Fix: add missing "where" type option

- docs/tutorials/building-a-new-site-wordpress-and-gatsby.md
- docs/tutorials/creating-a-new-site-from-a-starter.md
- docs/tutorials/index.md
- plugin/src/steps/preview/cleanup.ts
This PR adds a new tutorial explaining how to get started with the official blog starter.
> Docs: Add a "starting with a starter" tutorial

- CHANGELOG.md
- plugin/package.json
- yarn.lock
This vuln doesn't effect users of gatsby-source-wordpress-experimental since we're not using the proxy feature the vuln was related to but we need to upgrade since `npm audit` fails on this meaning we can't merge our starter into the monorepo
https://www.npmjs.com/advisories/1594
> fix: bump axios version
